server {
    listen 443 ssl;
    server_name ttanaka.42.fr;

    ssl_protocols TLSv1.3;
    ssl_certificate /run/secrets/nginx-server-crt;
    ssl_certificate_key /run/secrets/nginx-server-key;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /adminer {
        proxy_pass http://adminer:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /portfolio {
        proxy_pass http://static_website:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /homer {
        return 301 /homer/;
    }

    location /homer/ {
        proxy_pass http://homer:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
