services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/mysql
    networks:
      docker-network:
        ipv4_address: 172.20.0.4
    secrets:
      - db-password
      - db-root-password

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp-admin-password
      WP_PASSWORD_FILE: /run/secrets/wp-user-password
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: wp-vol
        target: /var/www/html
    networks:
      docker-network:
        ipv4_address: 172.20.0.3
    secrets:
      - db-password
      - wp-admin-password
      - wp-user-password

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - type: volume
        source: wp-vol
        target: /var/www/html
    ports:
      - "443:443"
    networks:
      docker-network:
        ipv4_address: 172.20.0.2
    secrets:
      - nginx-server-crt
      - nginx-server-key

volumes:
  db-vol:
    name: inception_db-vol-mac
  wp-vol:
    name: inception_wp-vol-mac

networks:
  docker-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

secrets:
  db-password:
    file: ../secrets/db_password.txt
  db-root-password:
    file: ../secrets/db_root_password.txt
  wp-admin-password:
    file: ../secrets/wp_admin_password.txt
  wp-user-password:
    file: ../secrets/wp_user_password.txt
  nginx-server-crt:
    file: ../secrets/nginx/server.crt
  nginx-server-key:
    file: ../secrets/nginx/server.key
